meta_product_name: "Nina"
meta_title: "Nina - Classic Yacht for Charter in Argentario, Tuscany"
meta_description: "Nina is an elegant and classic displacement yacht with timeless appeal, thoughtfully restored and equipped with all amenities and zero speed stabiliser, ready to explore the hidden beauties of the West Mediterranean."
meta_image: "about2.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
